source 'http://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'

# Use postgresql as the database for Active Record
gem 'pg'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# JSON Web Token implementation in Ruby
gem 'jwt', '~> 1.5.1'

# Backported from Rails 5.0 to use with 4.x versions
gem 'active_model-errors_details', '~> 1.1.1'

#Builds a tree of errors instead of the 1-dimension one generated by ActiveMode::Base#errors.messages.
gem 'activemodel-errors-tree', '~> 0.1.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Make any Ruby object quack like ActiveRecord
gem 'active_type', '~> 0.4.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Automatically generate an entity-relationship diagram (ERD) for your Rails models.
  gem 'rails-erd', '~> 1.4.2'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.3.3'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'capybara', '~> 2.5.0'
  gem 'guard-rspec', '~> 4.6.4'
  gem 'rb-fsevent'
end

# Easy and powerful exception tracking for Ruby
# gem 'rollbar', '~> 2.3.0'
